dist: trusty
language: scala
scala:
    - 2.12.4

# This may be necessary depending on the tests we eventually run. For example,
# the chaincode base server uses "java.util.Base64", which is only supported
# as of java version 8
jdk:
  - oraclejdk8

before_install:
  - ./travis_specific/install-protobuf.sh
  - ./travis_specific/install-bin.sh
  - export PATH=${PATH}:${HOME}/protobuf/
  - export PATH=${PATH}:${HOME}/bin/


script:
  - gradle publish -b Obsidian_Runtime/build.gradle
  - sbt ++2.12.4 test

deploy:
  provider: script
  script: bash travis_specific/tests.sh
  on:
    branch: getGuid